/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pablocompany.practica.no1.compi2.ui.frame;

import com.pablocompany.practica.no1.compi2.application.mediator.WorkspaceNotifier;
import com.pablocompany.practica.no1.compi2.infrastructure.controller.ProjectFileController;
import com.pablocompany.practica.no1.compi2.infrastructure.errors.CompilerError;
import com.pablocompany.practica.no1.compi2.infrastructure.semantic.Symbol;
import com.pablocompany.practica.no1.compi2.ui.components.bottom.BottomTabbedPanel;
import com.pablocompany.practica.no1.compi2.ui.components.editor.CodeEditorPanel;
import com.pablocompany.practica.no1.compi2.ui.components.sideview.SidePanel;
import com.pablocompany.practica.no1.compi2.ui.components.toast.ToastNotification;
import java.awt.BorderLayout;
import java.util.List;

/**
 *
 * @author pablo03
 */
//This clas is the main frame from de UI
public class MainFrame extends javax.swing.JFrame implements WorkspaceNotifier {

    private CodeEditorPanel editor;

    private SidePanel side;

    private BottomTabbedPanel bottom;

    //Controller for the file services
    private final ProjectFileController fileController;

    public MainFrame() {
        initComponents();
        initializeCustomComponents();
        attachComponents();

        this.fileController = new ProjectFileController();

    }

    private void initializeCustomComponents() {

        editor = new CodeEditorPanel(this);

        side = new SidePanel();

        bottom = new BottomTabbedPanel();

    }

    private void attachComponents() {

        editorPanel.setLayout(new BorderLayout());
        extraPanel.setLayout(new BorderLayout());
        bottomPanel.setLayout(new BorderLayout());

        editorPanel.add(editor, BorderLayout.CENTER);
        extraPanel.add(side, BorderLayout.CENTER);
        bottomPanel.add(bottom, BorderLayout.CENTER);
    }

    // ==========================================
    // WORKSPACENOTIFIER OBSERVER PATTERN IMPLEMENTATION
    // ==========================================
    @Override
    public void logInfo(String message) {
        bottom.getConsole().appendInfo(message);
    }

    @Override
    public void logSuccess(String message) {
        bottom.getConsole().appendSuccess(message);
    }

    @Override
    public void logError(String message) {
        bottom.getConsole().appendError(message);
    }

    @Override
    public void alertToast(String message, boolean isError) {
        ToastNotification.show(this, message, isError);
    }

    @Override
    public void focusConsole() {
        bottom.showConsole();
    }

    @Override
    public void focusErrors() {
        bottom.showErrors();
    }

    @Override
    public void focusSymbolsTable() {
        bottom.showSymbolsTable();
    }

    @Override
    public void clearLogs() {
        bottom.getConsole().clear();
        bottom.getErrors().clear();
    }

    @Override
    public void notifyErrorsUpdated(List<CompilerError> compilerErrors) {
        bottom.setCompilerErrors(compilerErrors);
    }

    @Override
    public void notifySymbolUpdated(List<Symbol> symbols) {
        bottom.setSymbols(symbols);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        separatorPanel1 = new javax.swing.JPanel();
        terminalButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        runButton1 = new javax.swing.JButton();
        mainContainer = new javax.swing.JPanel();
        verticalSplit = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        horizontalSplit = new javax.swing.JSplitPane();
        editorPanel = new javax.swing.JPanel();
        extraPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenuOption = new javax.swing.JMenu();
        fileMenu1 = new javax.swing.JMenuItem();
        fileMenu2 = new javax.swing.JMenuItem();
        fileMenu3 = new javax.swing.JMenuItem();
        toolsMenuOption = new javax.swing.JMenu();
        toolsMenu1 = new javax.swing.JMenuItem();
        toolsMenu2 = new javax.swing.JMenuItem();
        toolsMenu3 = new javax.swing.JMenuItem();
        reportMenuOption = new javax.swing.JMenu();
        reportMenu1 = new javax.swing.JMenuItem();
        reportMenu2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codex Compiler");
        setBackground(new java.awt.Color(220, 229, 196));
        setMinimumSize(new java.awt.Dimension(1400, 900));
        setPreferredSize(new java.awt.Dimension(1400, 900));

        mainPanel.setBackground(new java.awt.Color(225, 221, 166));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(175, 123, 128));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        headerPanel.setPreferredSize(new java.awt.Dimension(1300, 40));
        headerPanel.setLayout(new java.awt.GridBagLayout());

        separatorPanel1.setBackground(new java.awt.Color(175, 123, 128));
        separatorPanel1.setMinimumSize(new java.awt.Dimension(300, 10));
        separatorPanel1.setPreferredSize(new java.awt.Dimension(300, 10));

        javax.swing.GroupLayout separatorPanel1Layout = new javax.swing.GroupLayout(separatorPanel1);
        separatorPanel1.setLayout(separatorPanel1Layout);
        separatorPanel1Layout.setHorizontalGroup(
            separatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separatorPanel1Layout.setVerticalGroup(
            separatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 700, 0, 0);
        headerPanel.add(separatorPanel1, gridBagConstraints);

        terminalButton.setBackground(new java.awt.Color(0, 102, 102));
        terminalButton.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        terminalButton.setForeground(new java.awt.Color(255, 255, 255));
        terminalButton.setText("Abrir Terminal");
        terminalButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        terminalButton.setFocusPainted(false);
        terminalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        terminalButton.setMaximumSize(new java.awt.Dimension(120, 30));
        terminalButton.setMinimumSize(new java.awt.Dimension(120, 30));
        terminalButton.setPreferredSize(new java.awt.Dimension(120, 30));
        terminalButton.setRequestFocusEnabled(false);
        terminalButton.addActionListener(this::terminalButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 2);
        headerPanel.add(terminalButton, gridBagConstraints);

        runButton.setBackground(new java.awt.Color(0, 102, 51));
        runButton.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        runButton.setForeground(new java.awt.Color(255, 255, 255));
        runButton.setText("Compilar");
        runButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        runButton.setFocusPainted(false);
        runButton.setMaximumSize(new java.awt.Dimension(100, 30));
        runButton.setMinimumSize(new java.awt.Dimension(100, 30));
        runButton.setPreferredSize(new java.awt.Dimension(100, 30));
        runButton.addActionListener(this::runButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        headerPanel.add(runButton, gridBagConstraints);

        runButton1.setBackground(new java.awt.Color(204, 102, 0));
        runButton1.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        runButton1.setForeground(new java.awt.Color(255, 255, 255));
        runButton1.setText("Paso a Paso");
        runButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        runButton1.setFocusPainted(false);
        runButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        runButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        runButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        runButton1.addActionListener(this::runButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        headerPanel.add(runButton1, gridBagConstraints);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        mainContainer.setBorder(new javax.swing.border.MatteBorder(null));
        mainContainer.setRequestFocusEnabled(false);
        mainContainer.setLayout(new java.awt.BorderLayout());

        verticalSplit.setBackground(new java.awt.Color(0, 0, 0));
        verticalSplit.setBorder(new javax.swing.border.MatteBorder(null));
        verticalSplit.setDividerLocation(600);
        verticalSplit.setDividerSize(4);
        verticalSplit.setForeground(new java.awt.Color(0, 0, 0));
        verticalSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        verticalSplit.setLastDividerLocation(600);
        verticalSplit.setPreferredSize(new java.awt.Dimension(252, 251));

        topPanel.setMinimumSize(new java.awt.Dimension(600, 100));
        topPanel.setPreferredSize(new java.awt.Dimension(600, 100));
        topPanel.setLayout(new java.awt.BorderLayout());

        horizontalSplit.setBackground(new java.awt.Color(0, 0, 0));
        horizontalSplit.setDividerLocation(900);
        horizontalSplit.setDividerSize(4);

        editorPanel.setPreferredSize(new java.awt.Dimension(800, 599));

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        horizontalSplit.setLeftComponent(editorPanel);

        extraPanel.setBackground(new java.awt.Color(225, 221, 166));
        extraPanel.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        extraPanel.setPreferredSize(new java.awt.Dimension(600, 599));

        javax.swing.GroupLayout extraPanelLayout = new javax.swing.GroupLayout(extraPanel);
        extraPanel.setLayout(extraPanelLayout);
        extraPanelLayout.setHorizontalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        extraPanelLayout.setVerticalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        horizontalSplit.setRightComponent(extraPanel);

        topPanel.add(horizontalSplit, java.awt.BorderLayout.CENTER);

        verticalSplit.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(220, 229, 196));
        bottomPanel.setMinimumSize(new java.awt.Dimension(400, 100));
        bottomPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1406, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        verticalSplit.setBottomComponent(bottomPanel);

        mainContainer.add(verticalSplit, java.awt.BorderLayout.CENTER);

        mainPanel.add(mainContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(218, 188, 158));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setMinimumSize(new java.awt.Dimension(229, 35));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(229, 35));

        fileMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        fileMenuOption.setText("Archivo");

        fileMenu1.setText("Abrir Archivo");
        fileMenu1.addActionListener(this::fileMenu1ActionPerformed);
        fileMenuOption.add(fileMenu1);

        fileMenu2.setText("Guardar Archivo");
        fileMenu2.addActionListener(this::fileMenu2ActionPerformed);
        fileMenuOption.add(fileMenu2);

        fileMenu3.setText("Descargar Codigo");
        fileMenu3.addActionListener(this::fileMenu3ActionPerformed);
        fileMenuOption.add(fileMenu3);

        jMenuBar1.add(fileMenuOption);

        toolsMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        toolsMenuOption.setText("Herramientas");

        toolsMenu1.setText("Pila de procesos");
        toolsMenuOption.add(toolsMenu1);

        toolsMenu2.setText("Traduccion a PigLatin");
        toolsMenuOption.add(toolsMenu2);

        toolsMenu3.setText("Grafica del AST");
        toolsMenuOption.add(toolsMenu3);

        jMenuBar1.add(toolsMenuOption);

        reportMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        reportMenuOption.setText("Reportes");

        reportMenu1.setText("Tabla de Simbolos");
        reportMenuOption.add(reportMenu1);

        reportMenu2.setText("Reporte de errores");
        reportMenu2.addActionListener(this::reportMenu2ActionPerformed);
        reportMenuOption.add(reportMenu2);

        jMenuBar1.add(reportMenuOption);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminalButtonActionPerformed

    //This method uses the toast to notify and compile the code
    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        clearLogs();
        focusConsole();
        logInfo("Iniciando proceso de compilación...");

        boolean success = editor.compile(this);

        if (success) {
            alertToast("Compilación exitosa", false);
        } else {
            alertToast("Se encontraron errores en el código", true);
            focusErrors();
        }
    }//GEN-LAST:event_runButtonActionPerformed

    //Method to open a file
    private void fileMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenu1ActionPerformed
        fileController.handleOpen(this, editor.getEditor().getEditorContext(), () -> {
            editor.getEditor().setText(editor.getEditor().getEditorContext().getSourceCode());
        });
    }//GEN-LAST:event_fileMenu1ActionPerformed

    //Method to save a file
    private void fileMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenu2ActionPerformed
        editor.getEditor().getEditorContext().setSourceCode(editor.getEditor().getText());
        fileController.handleSave(this, editor.getEditor().getEditorContext());
    }//GEN-LAST:event_fileMenu2ActionPerformed

    //Method to save the compiled code
    private void fileMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenu3ActionPerformed
        fileController.handleExport(this, editor.getEditor().getEditorContext());
    }//GEN-LAST:event_fileMenu3ActionPerformed

    private void runButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runButton1ActionPerformed

    //This method redirect to the errors
    private void reportMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenu2ActionPerformed
        focusErrors();
    }//GEN-LAST:event_reportMenu2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JPanel extraPanel;
    private javax.swing.JMenuItem fileMenu1;
    private javax.swing.JMenuItem fileMenu2;
    private javax.swing.JMenuItem fileMenu3;
    private javax.swing.JMenu fileMenuOption;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSplitPane horizontalSplit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem reportMenu1;
    private javax.swing.JMenuItem reportMenu2;
    private javax.swing.JMenu reportMenuOption;
    private javax.swing.JButton runButton;
    private javax.swing.JButton runButton1;
    private javax.swing.JPanel separatorPanel1;
    private javax.swing.JButton terminalButton;
    private javax.swing.JMenuItem toolsMenu1;
    private javax.swing.JMenuItem toolsMenu2;
    private javax.swing.JMenuItem toolsMenu3;
    private javax.swing.JMenu toolsMenuOption;
    private javax.swing.JPanel topPanel;
    private javax.swing.JSplitPane verticalSplit;
    // End of variables declaration//GEN-END:variables

}
