/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pablocompany.practica.no1.compi2.ui.frame;

import com.pablocompany.practica.no1.compi2.application.mediator.WorkspaceNotifier;
import com.pablocompany.practica.no1.compi2.infrastructure.errors.CompilerError;
import com.pablocompany.practica.no1.compi2.ui.components.bottom.BottomTabbedPanel;
import com.pablocompany.practica.no1.compi2.ui.components.editor.CodeEditorPanel;
import com.pablocompany.practica.no1.compi2.ui.components.sideview.SidePanel;
import com.pablocompany.practica.no1.compi2.ui.components.toast.ToastNotification;
import java.awt.BorderLayout;
import java.util.List;

/**
 *
 * @author pablo03
 */
public class MainFrame extends javax.swing.JFrame implements WorkspaceNotifier {

    private CodeEditorPanel editor;

    private SidePanel side;

    private BottomTabbedPanel bottom;

    public MainFrame() {
        initComponents();
        initializeCustomComponents();
        attachComponents();

    }

    private void initializeCustomComponents() {

        editor = new CodeEditorPanel(this);

        side = new SidePanel();

        bottom = new BottomTabbedPanel();

    }

    private void attachComponents() {

        editorPanel.setLayout(new BorderLayout());
        extraPanel.setLayout(new BorderLayout());
        bottomPanel.setLayout(new BorderLayout());

        editorPanel.add(editor, BorderLayout.CENTER);
        extraPanel.add(side, BorderLayout.CENTER);
        bottomPanel.add(bottom, BorderLayout.CENTER);
    }

    // ==========================================
    // WORKSPACENOTIFIER OBSERVER PATTERN IMPLEMENTATION
    // ==========================================
    @Override
    public void logInfo(String message) {
        bottom.getConsole().appendInfo(message);
    }

    @Override
    public void logSuccess(String message) {
        bottom.getConsole().appendSuccess(message);
    }

    @Override
    public void logError(String message) {
        bottom.getConsole().appendError(message);
    }

    @Override
    public void alertToast(String message, boolean isError) {
        ToastNotification.show(this, message, isError);
    }

    @Override
    public void focusConsole() {
        bottom.showConsole();
    }

    @Override
    public void focusErrors() {
        bottom.showErrors();
    }

    @Override
    public void clearLogs() {
        bottom.getConsole().clear();
        bottom.getErrors().clear();
    }

    @Override
    public void notifyErrorsUpdated(List<CompilerError> compilerErrors) {
        bottom.setCompilerErrors(compilerErrors);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        separatorPanel1 = new javax.swing.JPanel();
        terminalButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        mainContainer = new javax.swing.JPanel();
        verticalSplit = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        horizontalSplit = new javax.swing.JSplitPane();
        editorPanel = new javax.swing.JPanel();
        extraPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenuOption = new javax.swing.JMenu();
        FileMenu1 = new javax.swing.JMenu();
        FileMenu2 = new javax.swing.JMenu();
        FileMenu3 = new javax.swing.JMenu();
        ToolsMenuOption = new javax.swing.JMenu();
        ToolsMenu1 = new javax.swing.JMenu();
        ToolsMenu2 = new javax.swing.JMenu();
        ToolsMenu3 = new javax.swing.JMenu();
        ReportMenuOption = new javax.swing.JMenu();
        ReportMenu1 = new javax.swing.JMenu();
        ReportMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codex Compiler");
        setBackground(new java.awt.Color(220, 229, 196));
        setMinimumSize(new java.awt.Dimension(1400, 900));
        setPreferredSize(new java.awt.Dimension(1400, 900));

        mainPanel.setBackground(new java.awt.Color(225, 221, 166));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(175, 123, 128));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        headerPanel.setPreferredSize(new java.awt.Dimension(1300, 40));
        headerPanel.setLayout(new java.awt.GridBagLayout());

        separatorPanel1.setBackground(new java.awt.Color(175, 123, 128));
        separatorPanel1.setMinimumSize(new java.awt.Dimension(300, 10));
        separatorPanel1.setPreferredSize(new java.awt.Dimension(300, 10));

        javax.swing.GroupLayout separatorPanel1Layout = new javax.swing.GroupLayout(separatorPanel1);
        separatorPanel1.setLayout(separatorPanel1Layout);
        separatorPanel1Layout.setHorizontalGroup(
            separatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separatorPanel1Layout.setVerticalGroup(
            separatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 750, 0, 0);
        headerPanel.add(separatorPanel1, gridBagConstraints);

        terminalButton.setBackground(new java.awt.Color(0, 102, 102));
        terminalButton.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        terminalButton.setForeground(new java.awt.Color(255, 255, 255));
        terminalButton.setText("Abrir Terminal");
        terminalButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        terminalButton.setFocusPainted(false);
        terminalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        terminalButton.setMaximumSize(new java.awt.Dimension(120, 30));
        terminalButton.setMinimumSize(new java.awt.Dimension(120, 30));
        terminalButton.setPreferredSize(new java.awt.Dimension(120, 30));
        terminalButton.setRequestFocusEnabled(false);
        terminalButton.addActionListener(this::terminalButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 2, 2);
        headerPanel.add(terminalButton, gridBagConstraints);

        runButton.setBackground(new java.awt.Color(0, 102, 51));
        runButton.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        runButton.setForeground(new java.awt.Color(255, 255, 255));
        runButton.setText("Compilar");
        runButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        runButton.setFocusPainted(false);
        runButton.setMaximumSize(new java.awt.Dimension(100, 30));
        runButton.setMinimumSize(new java.awt.Dimension(100, 30));
        runButton.setPreferredSize(new java.awt.Dimension(100, 30));
        runButton.addActionListener(this::runButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        headerPanel.add(runButton, gridBagConstraints);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        mainContainer.setBorder(new javax.swing.border.MatteBorder(null));
        mainContainer.setRequestFocusEnabled(false);
        mainContainer.setLayout(new java.awt.BorderLayout());

        verticalSplit.setBackground(new java.awt.Color(0, 0, 0));
        verticalSplit.setBorder(new javax.swing.border.MatteBorder(null));
        verticalSplit.setDividerLocation(600);
        verticalSplit.setDividerSize(4);
        verticalSplit.setForeground(new java.awt.Color(0, 0, 0));
        verticalSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        verticalSplit.setLastDividerLocation(600);
        verticalSplit.setPreferredSize(new java.awt.Dimension(252, 251));

        topPanel.setMinimumSize(new java.awt.Dimension(600, 100));
        topPanel.setPreferredSize(new java.awt.Dimension(600, 100));
        topPanel.setLayout(new java.awt.BorderLayout());

        horizontalSplit.setBackground(new java.awt.Color(0, 0, 0));
        horizontalSplit.setDividerLocation(900);
        horizontalSplit.setDividerSize(4);

        editorPanel.setPreferredSize(new java.awt.Dimension(800, 599));

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        horizontalSplit.setLeftComponent(editorPanel);

        extraPanel.setBackground(new java.awt.Color(225, 221, 166));
        extraPanel.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        extraPanel.setPreferredSize(new java.awt.Dimension(600, 599));

        javax.swing.GroupLayout extraPanelLayout = new javax.swing.GroupLayout(extraPanel);
        extraPanel.setLayout(extraPanelLayout);
        extraPanelLayout.setHorizontalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        extraPanelLayout.setVerticalGroup(
            extraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        horizontalSplit.setRightComponent(extraPanel);

        topPanel.add(horizontalSplit, java.awt.BorderLayout.CENTER);

        verticalSplit.setTopComponent(topPanel);

        bottomPanel.setBackground(new java.awt.Color(220, 229, 196));
        bottomPanel.setMinimumSize(new java.awt.Dimension(400, 100));
        bottomPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1314, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        verticalSplit.setBottomComponent(bottomPanel);

        mainContainer.add(verticalSplit, java.awt.BorderLayout.CENTER);

        mainPanel.add(mainContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(218, 188, 158));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setMinimumSize(new java.awt.Dimension(229, 35));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(229, 35));

        FileMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        FileMenuOption.setText("Archivo");

        FileMenu1.setBackground(new java.awt.Color(218, 188, 158));
        FileMenu1.setText("Abrir Archivo");
        FileMenuOption.add(FileMenu1);

        FileMenu2.setBackground(new java.awt.Color(218, 188, 158));
        FileMenu2.setText("Guardar Archivo");
        FileMenuOption.add(FileMenu2);

        FileMenu3.setBackground(new java.awt.Color(218, 188, 158));
        FileMenu3.setText("Descargar Archivo");
        FileMenuOption.add(FileMenu3);

        jMenuBar1.add(FileMenuOption);

        ToolsMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        ToolsMenuOption.setText("Herramientas");

        ToolsMenu1.setBackground(new java.awt.Color(218, 188, 158));
        ToolsMenu1.setText("Pila de procesos");
        ToolsMenuOption.add(ToolsMenu1);

        ToolsMenu2.setBackground(new java.awt.Color(218, 188, 158));
        ToolsMenu2.setText("Grafica del AST");
        ToolsMenuOption.add(ToolsMenu2);

        ToolsMenu3.setBackground(new java.awt.Color(218, 188, 158));
        ToolsMenu3.setText("Traduccion a PigLatin");
        ToolsMenuOption.add(ToolsMenu3);

        jMenuBar1.add(ToolsMenuOption);

        ReportMenuOption.setBackground(new java.awt.Color(175, 123, 128));
        ReportMenuOption.setText("Reportes");

        ReportMenu1.setBackground(new java.awt.Color(218, 188, 158));
        ReportMenu1.setText("Tabla de simbolos");
        ReportMenuOption.add(ReportMenu1);

        ReportMenu2.setBackground(new java.awt.Color(218, 188, 158));
        ReportMenu2.setText("Reporte de errores");
        ReportMenuOption.add(ReportMenu2);

        jMenuBar1.add(ReportMenuOption);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminalButtonActionPerformed

    //This method uses the toast to notify and compile the code
    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        clearLogs();
        focusConsole();
        logInfo("Iniciando proceso de compilación...");

        boolean success = editor.compile(this);

        if (success) {
            alertToast("Compilación exitosa", false);
        } else {
            alertToast("Se encontraron errores en el código", true);
            focusErrors();
        }
    }//GEN-LAST:event_runButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu1;
    private javax.swing.JMenu FileMenu2;
    private javax.swing.JMenu FileMenu3;
    private javax.swing.JMenu FileMenuOption;
    private javax.swing.JMenu ReportMenu1;
    private javax.swing.JMenu ReportMenu2;
    private javax.swing.JMenu ReportMenuOption;
    private javax.swing.JMenu ToolsMenu1;
    private javax.swing.JMenu ToolsMenu2;
    private javax.swing.JMenu ToolsMenu3;
    private javax.swing.JMenu ToolsMenuOption;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JPanel extraPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSplitPane horizontalSplit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton runButton;
    private javax.swing.JPanel separatorPanel1;
    private javax.swing.JButton terminalButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JSplitPane verticalSplit;
    // End of variables declaration//GEN-END:variables

}
